[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace  = true
space_engine.workspace = true
bevy_tweening.workspace = true

ui_core.path    = "../ui_core"
ui_loading.path = "../ui_loading"
ui_menu.path    = "../ui_menu"
ui_style.path   = "../ui_style"