[package]
name = "ui_loading"
version = "0.1.0"
edition = "2021"

[dependencies]
decay_engine.workspace = true
bevy.workspace = true
bevy_tweening.workspace = true
bevy_asset_loader.workspace = true
ui_core.path = "../ui_core"